service: calindra-desafio-serverless

frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    GOOGLE_GEOLOCATION_ACCESS_KEY: ${env:GOOGLE_GEOLOCATION_ACCESS_KEY}

  # you can overwrite defaults here
  stage: dev
  region: us-east-1  

functions:
  geolocation:
    handler: dist/controllers/geolocation/geolocation-controller.post
    events:
      - http:
          path: geolocation
          method: post

package:
 patterns:
   - dist/**
   # mantaining axios dist files only in node_modules
   - '!node_modules/**'
   - 'node_modules/axios/**'
   - 'node_modules/follow-redirects/**'
   - '!src/**'
 excludeDevDependencies: true